#!/bin/bash

# Variaveis
WIDTH=${WIDTH:-200}
HEIGHT=${HEIGHT:-200}

case "$BLOCK_BUTTON" in 
 1|2|3)

	# posição da janela
	posX=$(($BLOCK_X - $WIDTH / 2))
	posY=$(($BLOCK_Y - $HEIGHT))

#Comando

i3-msg -q "exec yad --calendar --width=$WIDTH --height=$HEIGHT --undecorate --fixed --close-on-unfocus --no-buttons --posx=$posX --posy=$posY > /dev/null"

esac

echo "$(date '+%d/%m/%Y') "
