# Define o tipo de terminal
set -g default-terminal "xterm-256color"

# Habilita cores de 24 bits
set -sa terminal-overrides ",xterm-256color:Tc"

# Configura o atraso da tecla ESC para 0ms
set -s escape-time 0

# Habilita o mouse
set -g mouse on

# Configura o tamanho o lado esquerdo da barra de status
set -g status-left-length 40

# Índice inicial de janelas e paineis
set -g base-index 1
set -g pane-base-index 1
